/*Hajjami Manal & Hamza Argane 2 AP G1 MAARIF*/

var catalogue =[ 
    {   code : 101,
        nom : "[BTS] - WORLD OST ALBUM ",
        desc: "CD + Photobook + Photocard + Lenticular + Game coupon & Official poster",
        prix: 500,
		image : "../image/img101.jpg",
    },
    {   code : 200,
        nom : "TXT - THE DREAM CHAPTER : ETERNITY ",
        desc: "Port Ver./ Starboard Ver + CD + Photobook + Photocard A + Photocard B + Stickers + Poster",
        prix: 400,
		image : "../image/img200.jpg",
    },
    {   code : 300,
        nom  : "ONF - 'GO LIVE' 4th Mini Album" , 
        desc : "Poster + 100p Booklet + 2p Morse Message Card + Message PhotoCard SET + 2p Selfie PhotoCard" , 
        prix :240,
		image : "../image/img300.jpg",
    },
    {   code : 402,
        nom: "RED VELVET 2nd Repackage Album - [ BAD BOY : THE PERFECT RED VELVET ] ",
        desc: "CD + PhotoBook + PhotoCard + FREE GIFT ",
        prix: 290,
		image : "../image/img402.jpg" ,
    },
    {   code : 500,
        nom  : " Billie Eilish - When We All Fall Asleep Where Do We Go" , 
        desc : "CD with 3 bonus titles" , 
        prix :80,
		image : "../image/img500.jpg",
    },
    {   code : 600,
        nom  : "Arctic monkeys - AM album  " , 
        desc : "Delux vinyl edition" , 
        prix :140,
		image : "../image/img600.jpg",
    },
    {   code : 700,
        nom  : " THE ROSE - void (1st Mini Album)" , 
        desc : "CD + Booklet + Photocard" , 
        prix :200,
		image : "../image/img700.jpg"
    },
    {   code : 800,
        nom  : "Halsey - Badlands" , 
        desc : "vinyl edition" , 
        prix :240,
		image : "../image/img800.jpg",
    },
    {   code : 900,
        nom  : " DAY6 - Shoot Me : Youth Part 1" , 
        desc : "- CD + Booklet + Clear Card + Tatoo Sticker + Photocards + Pop-up card+ Polaroid with Autograph" , 
        prix :249,
		image : "../image/img900.jpg" ,
    },
    {   code : 1000,
        nom  : "DAY6 4th Mini Album - Remember Us : Youth Part 2" ,
        desc : "CD + Photobook + Clear Card + Decoration Sticker + Photocard + Postcard + FREE GIFT " , 
        prix :219,
		image : "../image/img1000.jpg",
    },
    {   code : 1100,
        nom  : "DAY6 3rd Album - The Book Of Us : ENTROPY [ CHAOS ver. ]" , 
        desc : "CD + Photobook + Photocards + Postcard + Bookmark + FREE GIFT" , 
        prix :80,
		image : "../image/img1100.jpg" ,
    },
    {   code : 1200,
        nom  : "TWICE 4th Mini Album - SIGNAL" , 
        desc : "CD + Photobook + Photocard + Special Photocard + Photo + FREE GIFT" , 
        prix :270,
		image : "../image/img1200.jpg",
    },
    {   code : 1300,
        nom  : "Stray Kids - GO LIVE Limited ver." , 
        desc : "CD + Package Box + Photobook + Photocards + Unit Lyric Leaflet + 4-Cut Film + Secret Card Set + Special Photocard + Mini Standing Card + Polaroid + Poster " , 
        prix :390,
		image : "../image/img1300.jpg",
    },
    {   code : 1400,
        nom  : "BIGBANG - [MADE THE FULL ALBUM]  " , 
        desc : "CD + Photo Book + Photo Card + Puzzle Ticket + Puzzle Ticket Pad + Gift" , 
        prix :340,
		image : "../image/img1400.jpg",
    },
    {   code : 1500,
        nom  : "2Nd Album Nct #127 Neo Zone" , 
        desc : "Photo Book + Lyric Book + Postcard + Folded Poster + Sticker + Circle Card + Photo Card" , 
        prix :219,
		image : "../image/img1500.jpg",
    },
    {   code : 1600,
        nom  : "EXO 5th Album - Don't Mess Up My Tempo" , 
        desc : " CD + Booklet + Photocard + FREE GIFT" , 
        prix :190,
		image : "../image/img1600.jpg",
    },
    {   code : 1700,
        nom  : "EXO - OBSESSION 6TH ALBUM" , 
        desc : "CD + Folded Poster + Photocards + Photobook " , 
        prix :270,
		image : "../image/img1700.jpg",
    },
    {   code : 1800,
        nom  : "BTS 1st Album - [ DARK & WILD ]" , 
        desc : " CD + Photobook + Photocard + FREE GIFT" , 
        prix :270,
		image : "../image/img1800.jpg",
    },
    {   code : 1900,
        nom  : "APRIL - 6th Mini Album: The Ruby" , 
        desc : "CD+PhotoBook+M.Poster+2pCard+Tracking Number" , 
        prix :170,
		image : "../image/img1900.jpg",
    },
    {   code : 2000,
        nom  : "Square Up [ BLACK Ver. ] - BLACKPINK 1st Mini Album" , 
        desc : "CD + Photo Book + Lyrics Book + Postcard + Photocard + FREE GIFT " , 
        prix :270,
		image : "../image/img2000.jpg",
    },
 ]
 var promo =[ 
   
    {   code : 2001,
        nom : " Tomorrow X Together Album - The Dream Chapter ",
        desc: "Star CD + Photobook + Photocards + Sticker Pack + OFFICIAL POSTER ",
        prixan: 500,
        prix: 350,
		image : "image/img2001.jpg",
    },
    {   code : 2002,
        nom : " BAEKHYUN The 1st Mini Album 'City Lights'",
        desc: "CD + Photobook + Lyrics Booklet + Folded Poster(On pack) + Photocard ",
        prixan: 400,
        prix: 280,
		image : "image/img2002.jpg",
    },
    {   code : 2003,
        nom : "ITZY - 'IT'z Different' Album  ",
        desc: "CD + Photobook + Photocard ",
        prixan: 450,
        prix: 315,
		image : "image/img2003.jpg",
    },
    ]
